# Generated by Django 4.2.2 on 2023-06-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='services',
            field=models.CharField(choices=[('', 'Select'), ('Vaccination', 'Vaccinations'), ('Medical_Report', 'Medical Reports'), ('General_Care', 'General Care'), ('Routine_check-up_lab_test', 'Routine check-up and lab tests'), ('Other', 'Others')], default='', max_length=30),
        ),
    ]
